# Generated by Django 4.1.4 on 2023-09-15 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robotics', '0003_rename_slugs_greroboticsmodel_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='greroboticsmodel',
            name='category',
            field=models.CharField(default='coding', max_length=250),
        ),
    ]
