# Generated by Django 4.1.4 on 2023-10-03 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robotics', '0004_category_greroboticsmodel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greroboticsmodel',
            name='category',
            field=models.CharField(default='coding', max_length=255),
        ),
    ]
